export const THINKING_MARKDOWN_CLASS = [
  '[&_h1]:m-0',
  '[&_h1]:mb-1',
  '[&_h1]:text-inherit',
  '[&_h1]:font-semibold',
  '[&_h2]:m-0',
  '[&_h2]:mb-1',
  '[&_h2]:text-inherit',
  '[&_h2]:font-semibold',
  '[&_h3]:m-0',
  '[&_h3]:mb-1',
  '[&_h3]:text-inherit',
  '[&_h3]:font-semibold',
  '[&_strong]:font-semibold',
  '[&_blockquote]:my-1',
  '[&_blockquote]:border-l-2',
  '[&_blockquote]:border-app-border-subtle',
  '[&_blockquote]:pl-2',
  '[&_blockquote]:text-inherit',
  '[&_p]:m-0',
  '[&_p]:mb-1.5',
  '[&_p:last-child]:mb-0',
].join(' ')
