package query

import "sync"

// TitleBroker fans out AI-generated session titles to active streams. Title
// persistence remains owned by SessionOwnershipStore; this is only the live UI
// notification path for the first-turn title generated by the SDK.
type TitleBroker struct {
	mu          sync.Mutex
	subscribers map[string]map[chan string]struct{}
}

func NewTitleBroker() *TitleBroker {
	return &TitleBroker{subscribers: make(map[string]map[chan string]struct{})}
}

func (b *TitleBroker) Subscribe(sessionID string) (<-chan string, func()) {
	if b == nil || sessionID == "" {
		ch := make(chan string)
		close(ch)
		return ch, func() {}
	}
	ch := make(chan string, 1)
	b.mu.Lock()
	if b.subscribers == nil {
		b.subscribers = make(map[string]map[chan string]struct{})
	}
	if b.subscribers[sessionID] == nil {
		b.subscribers[sessionID] = make(map[chan string]struct{})
	}
	b.subscribers[sessionID][ch] = struct{}{}
	b.mu.Unlock()

	return ch, func() {
		b.mu.Lock()
		if subs := b.subscribers[sessionID]; subs != nil {
			delete(subs, ch)
			if len(subs) == 0 {
				delete(b.subscribers, sessionID)
			}
		}
		b.mu.Unlock()
		close(ch)
	}
}

func (b *TitleBroker) Notify(sessionID, title string) {
	if b == nil || sessionID == "" || title == "" {
		return
	}
	b.mu.Lock()
	defer b.mu.Unlock()
	for ch := range b.subscribers[sessionID] {
		select {
		case ch <- title:
		default:
		}
	}
}
